### ISSUE TITLE
As a user, I want to ask questions to evolve as a developer

### ISSUE THREAD

**Issue by Andre05-vikk** [Andre05-vikk/it-mentor#1]
- [ ]  There is a button "Add a question"
- [ ]  Clicking this button opens a modal
- [ ]  In modal, there is a text area to enter a question and a button to send it
- [ ]  Clicking the button sends the question to the server, and it is saved in the database
- [ ]  If the text area is empty the button is disabled
- [ ]  If there are more than 1000 characters in the text area, the text "The maximum text length is 1000 characters" appears in red under the text area and the button is disabled

**Comment by sanderprii** [comment]
![image](https://github.com/user-attachments/assets/88423399-8e9d-4fb9-b960-2528be90b2e7)

**Comment by Andre05-vikk** [comment]
![Screenshot 2024-10-23 183419](https://github.com/user-attachments/assets/d80aef12-b141-440d-a210-96b8284d839d)
